version: "3"

services:
  db:
    container_name: spring-postgres
    image: postgres
    restart: unless-stopped

    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      PGDATA: /data/postgres

    ports:
      - "5432:5432"
    volumes:
      - db:/data/postgres

volumes:
  db: